apiVersion: opg.ewbi.katalis.com/v1beta1
kind: AvailabilityZone
metadata:
  namespace: guest
  name: zone-123e4567
spec:
  relationType: GUEST
  federationContextId: c02456b8f-f53e-5894-921e-03c7db7e0ec6
  zoneId: 123e4567-e89b-12d3-a456-426614174000
  zoneNotifLink: "http://katalis-fm-api.host.svc.cluster.local:8080"