version: "3.8"

secrets:
  netrc:
    #file: /Users/${USER}/.netrc # For Mac
    file: /home/${USER}/.netrc

services:
  federation:
    image: ghcr.io/neonephos-katalis/opg-ewbi-api:dev-callback-1.1.1
    build:
      context: ./
      dockerfile: Dockerfile.api
      secrets:
        - netrc
    env_file:
      - .env
    restart: on-failure
    #platform: linux/arm64
    platform: linux/amd64
    ports:
      - "8080:8080"

  federation-debug:
    image: ghcr.io/neonephos-katalis/opg-ewbi-api:neonephos-debug
    build:
      context: ./
      dockerfile: Dockerfile
      target: debug
      secrets:
        - netrc
    env_file:
      - .env
    restart: on-failure
    platform: linux/arm64
    # platform: linux/amd64
    ports:
      - "8080:8080"

  apigen:
    build:
      context: ./
      dockerfile: Dockerfile.apigen
    #platform: linux/arm64
    platform: linux/amd64
    volumes:
      - ./api/ewbi:/api/ewbi

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    #platform: linux/arm64
    platform: linux/amd64
    ports:
      - "8082:8080"
    volumes:
      - ./api/ewbi/FederationApi_v1.3.0.yaml:/usr/share/nginx/html/doc/swagger.yaml
    environment:
      API_URL: doc/swagger.yaml
