apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: opg-ewbi-host-delete-protection-policy-{{ .Release.Namespace }}
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups: ["opg.ewbi.katalis.com"]
      apiVersions: ["v1beta1"]
      operations: ["DELETE"]
      resources:
      - federations
      - images
      - artefacts
      - availabilityzones
      - applicationonboardings
      - applicationdeployments
  matchConditions:
  - name: exclude-controller-manager
    # WARNING update the following line with the correct name for guest's service account
    expression: >-
      request.userInfo.username != "system:serviceaccount:host:guest-sa"
  validations:
  - expression: >-
      !(
        request.resource.resource == "federations"
          ? (has(oldObject.spec.federationData) && has(oldObject.spec.federationData.relationType) && oldObject.spec.federationData.relationType == "HOST")
          : (has(oldObject.spec) && has(oldObject.spec.relationType) && oldObject.spec.relationType == "HOST")
      )
    messageExpression: >-
      "deletion of HOST-relation resources is prohibited except by the controller-manager itself (received identity: '" + request.userInfo.username + "')"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: opg-ewbi-host-delete-protection-policy-{{ .Release.Namespace }}-binding
spec:
  policyName: opg-ewbi-host-delete-protection-policy-{{ .Release.Namespace }}
  validationActions: ["Deny"]
  matchResources:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: {{ .Release.Namespace }}
