---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingadmissionpolicies
  - validatingadmissionpolicybindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: foo
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opg.ewbi.katalis.com
  resources:
  - applicationdeployments
  - applicationonboardings
  - artefacts
  - availabilityzones
  - federations
  - images
  verbs:
  - '*'
- apiGroups:
  - opg.ewbi.katalis.com
  resources:
  - applicationdeployments/finalizers
  - applicationonboardings/finalizers
  - artefacts/finalizers
  - availabilityzones/finalizers
  - federations/finalizers
  - images/finalizers
  verbs:
  - update
- apiGroups:
  - opg.ewbi.katalis.com
  resources:
  - applicationdeployments/status
  - applicationonboardings/status
  - artefacts/status
  - availabilityzones/status
  - federations/status
  - images/status
  verbs:
  - get
  - patch
  - update
