apiVersion: opg.ewbi.nby.one/v1beta1
kind: Federation
metadata:
  namespace: guest
  annotations:
    opg.ewbi.nby.one/origin-client-id: 3acde22c-d245-480d-b01e-24e38e01806e
  labels:
    opg.ewbi.nby.one/federation-relation: guest
    opg.ewbi.nby.one/host-operator-org-id: hostName
    # opg.ewbi.nby.one/origin-operator-org-id: "placeholder"
    opg.ewbi.nby.one/id: fed-guest-rest
    opg.ewbi.k8s/federation-technology: rest
  name: fed-guest-rest
spec:
  originOP:
    countryCode: "ES"
    fixedNetworkCodes:
      - "none"
    mobileNetworkCodes:
      mcc: "999"
      mncs:
        - "99"
  guestPartnerCredentials:
    clientId: 3acde22c-d245-480d-b01e-24e38e01806e
    tokenUrl: "http://tim-fm-api.host.svc.cluster.local:6443"
  partner:
    callbackCredentials:
      clientId: 5tyde22c-d245-480d-b01e-24e38e7689de
    statusLink: "http://tim-fm-api.guest.svc.cluster.local:6443"
