apiVersion: opg.ewbi.nby.one/v1beta1
kind: Federation
metadata:
  namespace: katalis-dev-guest
  annotations:
    opg.ewbi.nby.one/origin-client-id: 3acde22c-d245-480d-b01e-24e38e01806d
  labels:
    opg.ewbi.nby.one/federation-relation: guest
    opg.ewbi.nby.one/host-operator-org-id: host-name
    # opg.ewbi.nby.one/origin-operator-org-id: "placeholder"
    opg.ewbi.nby.one/id: fed-guest-k8s

    opg.ewbi.k8s/federation-technology: k8s
    opg.ewbi.k8s/secret-name: kubeconfig-secret
    opg.ewbi.k8s/namespace: katalis-host
    opg.ewbi.k8s/host-id: fed-host-k8s
  name: fed-guest-k8s
spec:
  originOP:
    countryCode: "ES"
    fixedNetworkCodes:
      - "none"
    mobileNetworkCodes:
      mcc: "999"
      mncs:
        - "99"
  guestPartnerCredentials:
    clientId: 3acde22c-d245-480d-b01e-24e38e01806d
    tokenUrl: "http://nearbyone-federation-api.katalis-dev-host.svc.cluster.local:8080"
  partner:
    callbackCredentials:
      clientId: 5tyde22c-d245-480d-b01e-24e38e7689de
    statusLink: "http://nearbyone-federation-api.katalis-dev-guest.svc.cluster.local:8080"
