apiVersion: opg.ewbi.nby.one/v1beta1
kind: File
metadata:
  namespace: guest
  labels:
    opg.ewbi.nby.one/federation-context-id: dc81e752-d230-5c7e-9bb1-e8cc4b59f828 # get this from Guest Federation's status
    opg.ewbi.nby.one/federation-relation: "guest"
    opg.ewbi.nby.one/federation-callback-id: 5tyde22c-d245-480d-b01e-24e38e7689de
    opg.ewbi.nby.one/id: file-rest
  name: file-rest
spec:
  appProviderId: nearbycomputing
  fileName: "nginx:latest"
  fileType: DOCKER
  fileVersion: "latest"
  image:
    instructionSetArchitecture: ISA_X86_64
    os:
      architecture: x86_64
      distribution: UBUNTU
      license: OS_LICENSE_TYPE_FREE
      version: OS_VERSION_UBUNTU_2204_LTS
  repoLocation:
    password: repoPass
    token: repoAccessToken
    type: public
    url: "docker.io"
    username: repoUser