apiVersion: v1
kind: ServiceAccount
metadata:
  name: katalis-guest-sa
  namespace: katalis-dev-host
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: katalis-guest-manager
rules:
- apiGroups: ["opg.ewbi.nby.one"] 
  resources: ["federations", "federations/status", "files", "files/status", "artefacts", "artefacts/status", "applications", "applications/status", "applicationinstances", "applicationinstances/status"] 
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: katalis-guest-binding
  namespace: katalis-dev-host
subjects:
- kind: ServiceAccount
  name: katalis-guest-sa
  namespace: katalis-dev-host
roleRef:
  kind: ClusterRole
  name: katalis-guest-manager
  apiGroup: rbac.authorization.k8s.io