apiVersion: opg.ewbi.nby.one/v1beta1
kind: ApplicationInstance
metadata:
  namespace: katalis-dev-guest
  labels:
    opg.ewbi.nby.one/federation-context-id: 4d559f1b-f008-58c2-a2f8-0596892a0f7a # get this from Guest Federation's status
    opg.ewbi.nby.one/federation-relation: "guest"
    opg.ewbi.nby.one/id: app-inst-k8s
  name: app-inst-k8s
spec:
  appId: app-k8s
  appProviderId: nearbycomputing
  appVersion: 1.23.3
  zoneInfo:
    flavourId: NOT_SPECIFIED
    resPool: mock-res-pool
    resourceConsumption: RESERVED_RES_AVOID
    zoneId: "zone-es-madrid-001"
