/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// finalizers
const (
	ApplicationDeploymentFinalizer = "katalis.com/applicationdeployment.opg.ewbi.finalizer"
)

type ApplicationDeploymentState string

// type ApplicationDeploymentK8sErrMsg string
// type ApplicationDeploymentK8sUnErrMsg string
type PluralApplicationDeploymentValue string
type KindApplicationDeploymentValue string

// type ApplicationDeploymentRestErrMsg string

const (
	ApplicationDeploymentStatePending     ApplicationDeploymentState = "PENDING"
	ApplicationDeploymentStateReady       ApplicationDeploymentState = "READY"
	ApplicationDeploymentStateFailed      ApplicationDeploymentState = "FAILED"
	ApplicationDeploymentStateTerminating ApplicationDeploymentState = "TERMINATING"

	PluralApplicationDeployment = "applicationdeployments"
	KindApplicationDeployment   = "ApplicationDeployment"
)

// ZoneInfo defines the zone information for the application
type ZoneInfo struct {
	// +kubebuilder:validation:Optional
	// An identifier to refer to a specific combination of compute resources
	FlavourId string `json:"flavourId,omitempty"`

	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Enum=RESERVED_RES_SHALL;RESERVED_RES_PREFER;RESERVED_RES_AVOID;RESERVED_RES_FORBID
	// +kubebuilder:default=RESERVED_RES_AVOID
	// Specifies if the application can be instantiated using pre-reserved resource or not.  App provider can pre-reserve a pool of compute resource on each zone.  'RESERVED_RES_SHALL' instruct OP to use only the pre-reserved resources. 'RESERVED_RES_PREFER' instruct to first try using pre-reserved resource, if none available go for non-reserved resources. 'RESERVED_RES_AVOID' instruct OP not to use pre-reserved resource if possible, it is a choice depending upon circumstances 'RESERVED_RES_FORBID' instruct OP not to use pre-reserved resources.
	ResourceConsumption string `json:"resourceConsumption,omitempty"`

	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Pattern=`^[A-Za-z0-9][A-Za-z0-9_]{6,30}[A-Za-z0-9]$`
	// Resource pool to be used for application instantiation on this zone.  Valid only if IE 'resourceConsumption' is set to 'RESERVED_RES_SHALL' or 'RESERVED_RES_PREFER'
	ResPool string `json:"resPool,omitempty"`
}

// AppDetails defines the application details
type AppDetails struct {
	// +kubebuilder:validation:Required
	// Version info of the application
	AppVersion string `json:"appVersion,omitempty"`

	// +kubebuilder:validation:Required
	ZoneInfo *ZoneInfo `json:"zoneInfo,omitempty"`

	// +kubebuilder:validation:Optional
	AppInstCallbackLink string `json:"appInstCallbackLink,omitempty"`
}

// +kubebuilder:validation:XValidation:rule="has(self.fqdn) || has(self.ipv4Addresses) || has(self.ipv6Addresses)",message="at least one among fqdn, ipv4Addresses, ipv6Addresses must be set"
type AccessPoints struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Minimum=0
	Port int `json:"port"`

	// +kubebuilder:validation:Optional
	// DNS FQDN assigned to application instances in an availability zone. User Clients can resolve the FQDN to communicate with the edge instances of the application
	Fqdn string `json:"fqdn,omitempty"`

	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:MinItems=1
	Ipv4Addresses []string `json:"ipv4Addresses,omitempty"`

	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:items:Format=ipv6
	// +kubebuilder:validation:items:Pattern=`^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$`
	Ipv6Addresses []string `json:"ipv6Addresses,omitempty"`
}

type AccessPointInfo struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^[A-Za-z0-9][A-Za-z0-9_]{6,30}[A-Za-z0-9]$`
	// This is the interface identifier that app provider defines when application is onboarded.
	InterfaceId string `json:"interfaceId"`

	// +kubebuilder:validation:Required
	AccessPoints *AccessPoints `json:"accessPoints"`
}

type AppInstanceInfo struct {
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Pattern=`^[A-Za-z0-9][A-Za-z0-9_]{6,62}[A-Za-z0-9]$`
	// Unique identifier generated by the partner OP to identify an instance of the application on a specific zone.
	AppInstIdentifier string `json:"appInstIdentifier,omitempty"`

	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=PENDING;READY;FAILED;TERMINATING
	// Running status of the application instance.
	AppInstanceState ApplicationDeploymentState `json:"appInstanceState"`
}

// ApplicationDeploymentSpec defines the desired state of ApplicationDeployment
type ApplicationDeploymentSpec struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=HOST;GUEST
	RelationType string `json:"relationType"`

	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^[A-Za-z0-9][A-Za-z0-9-]*$`
	// This identifier shall be provided by the partner OP on successful verification and validation of the federation create request and is used by partner op to identify this newly created federation context. Originating OP shall provide this identifier in any subsequent request towards the partner op.
	FederationContextId string `json:"federationContextId"`

	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Format=uuid
	// A unique transaction id for this request in UUID format. It is used for tracking the request
	TransactionId string `json:"transactionId,omitempty"`

	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^[A-Za-z][A-Za-z0-9_]{7,63}$`
	// Identifier used to refer to an application.
	AppId string `json:"appId,omitempty"`

	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^[A-Za-z0-9][A-Za-z0-9_]{6,62}[A-Za-z0-9]$`
	// Unique identifier generated by the partner OP to identify an instance of the application on a specific zone.
	AppInstanceId string `json:"appInstanceId,omitempty"`

	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^[A-Za-z0-9][A-Za-z0-9-]*$`
	// Human readable name of the zone.
	ZoneId string `json:"zoneId,omitempty"`

	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^[A-Za-z][A-Za-z0-9_]{7,63}$`
	// UserId of the app provider.  Identifier is relevant only in context of this federation.
	AppProviderId string `json:"appProviderId,omitempty"`

	// +kubebuilder:validation:Required
	AppDetails *AppDetails `json:"appDetails,omitempty"`
}

// ApplicationDeploymentStatus defines the observed state of ApplicationDeployment.
type ApplicationDeploymentStatus struct {
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:MinItems=1
	// Information about the IP and Port exposed by the OP. Application clients shall use these access points to reach this application instance
	AccessPointInfo []AccessPointInfo `json:"accessPointInfo,omitempty"`

	// +kubebuilder:validation:Optional
	AppInstanceInfo AppInstanceInfo `json:"appInstanceInfo,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=appdep,scope=Namespaced
// +kubebuilder:printcolumn:name="relationType",type="string",JSONPath=".spec.relationType"
// +kubebuilder:printcolumn:name="federationContextId",type="string",JSONPath=".spec.federationContextId"
// +kubebuilder:printcolumn:name="appId",type="string",JSONPath=".spec.appId"
// +kubebuilder:printcolumn:name="zoneId",type="string",JSONPath=".spec.zoneId"
// +kubebuilder:printcolumn:name="appInstanceId",type="string",JSONPath=".spec.appInstanceId"
// +kubebuilder:printcolumn:name="state",type="string",JSONPath=".status.appInstanceInfo.appInstanceState"

// ApplicationDeployment is the Schema for the applicationdeployments API
type ApplicationDeployment struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`
	// +required
	Spec ApplicationDeploymentSpec `json:"spec"`

	// +optional
	Status ApplicationDeploymentStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

// ApplicationDeploymentList contains a list of ApplicationDeployment
type ApplicationDeploymentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []ApplicationDeployment `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ApplicationDeployment{}, &ApplicationDeploymentList{})
}
