//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPointInfo) DeepCopyInto(out *AccessPointInfo) {
	*out = *in
	if in.AccessPoints != nil {
		in, out := &in.AccessPoints, &out.AccessPoints
		*out = new(AccessPoints)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPointInfo.
func (in *AccessPointInfo) DeepCopy() *AccessPointInfo {
	if in == nil {
		return nil
	}
	out := new(AccessPointInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPoints) DeepCopyInto(out *AccessPoints) {
	*out = *in
	if in.Ipv4Addresses != nil {
		in, out := &in.Ipv4Addresses, &out.Ipv4Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ipv6Addresses != nil {
		in, out := &in.Ipv6Addresses, &out.Ipv6Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPoints.
func (in *AccessPoints) DeepCopy() *AccessPoints {
	if in == nil {
		return nil
	}
	out := new(AccessPoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppComponentSpec) DeepCopyInto(out *AppComponentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppComponentSpec.
func (in *AppComponentSpec) DeepCopy() *AppComponentSpec {
	if in == nil {
		return nil
	}
	out := new(AppComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDeploymentZone) DeepCopyInto(out *AppDeploymentZone) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDeploymentZone.
func (in *AppDeploymentZone) DeepCopy() *AppDeploymentZone {
	if in == nil {
		return nil
	}
	out := new(AppDeploymentZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDetails) DeepCopyInto(out *AppDetails) {
	*out = *in
	if in.ZoneInfo != nil {
		in, out := &in.ZoneInfo, &out.ZoneInfo
		*out = new(ZoneInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDetails.
func (in *AppDetails) DeepCopy() *AppDetails {
	if in == nil {
		return nil
	}
	out := new(AppDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppIdList) DeepCopyInto(out *AppIdList) {
	*out = *in
	if in.ZoneIds != nil {
		in, out := &in.ZoneIds, &out.ZoneIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppIdList.
func (in *AppIdList) DeepCopy() *AppIdList {
	if in == nil {
		return nil
	}
	out := new(AppIdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppInfo) DeepCopyInto(out *AppInfo) {
	*out = *in
	if in.AppDeploymentZones != nil {
		in, out := &in.AppDeploymentZones, &out.AppDeploymentZones
		*out = make([]AppDeploymentZone, len(*in))
		copy(*out, *in)
	}
	if in.AppMetaData != nil {
		in, out := &in.AppMetaData, &out.AppMetaData
		*out = new(AppMetaData)
		**out = **in
	}
	if in.AppQoSProfile != nil {
		in, out := &in.AppQoSProfile, &out.AppQoSProfile
		*out = new(AppQoSProfile)
		**out = **in
	}
	if in.AppComponentSpecs != nil {
		in, out := &in.AppComponentSpecs, &out.AppComponentSpecs
		*out = make([]AppComponentSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppInfo.
func (in *AppInfo) DeepCopy() *AppInfo {
	if in == nil {
		return nil
	}
	out := new(AppInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppInstanceInfo) DeepCopyInto(out *AppInstanceInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppInstanceInfo.
func (in *AppInstanceInfo) DeepCopy() *AppInstanceInfo {
	if in == nil {
		return nil
	}
	out := new(AppInstanceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppMetaData) DeepCopyInto(out *AppMetaData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppMetaData.
func (in *AppMetaData) DeepCopy() *AppMetaData {
	if in == nil {
		return nil
	}
	out := new(AppMetaData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppQoSProfile) DeepCopyInto(out *AppQoSProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppQoSProfile.
func (in *AppQoSProfile) DeepCopy() *AppQoSProfile {
	if in == nil {
		return nil
	}
	out := new(AppQoSProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationDeployment) DeepCopyInto(out *ApplicationDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationDeployment.
func (in *ApplicationDeployment) DeepCopy() *ApplicationDeployment {
	if in == nil {
		return nil
	}
	out := new(ApplicationDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationDeploymentList) DeepCopyInto(out *ApplicationDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationDeploymentList.
func (in *ApplicationDeploymentList) DeepCopy() *ApplicationDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ApplicationDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationDeploymentSpec) DeepCopyInto(out *ApplicationDeploymentSpec) {
	*out = *in
	if in.AppDetails != nil {
		in, out := &in.AppDetails, &out.AppDetails
		*out = new(AppDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationDeploymentSpec.
func (in *ApplicationDeploymentSpec) DeepCopy() *ApplicationDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationDeploymentStatus) DeepCopyInto(out *ApplicationDeploymentStatus) {
	*out = *in
	if in.AccessPointInfo != nil {
		in, out := &in.AccessPointInfo, &out.AccessPointInfo
		*out = make([]AccessPointInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.AppInstanceInfo = in.AppInstanceInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationDeploymentStatus.
func (in *ApplicationDeploymentStatus) DeepCopy() *ApplicationDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationOnboarding) DeepCopyInto(out *ApplicationOnboarding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationOnboarding.
func (in *ApplicationOnboarding) DeepCopy() *ApplicationOnboarding {
	if in == nil {
		return nil
	}
	out := new(ApplicationOnboarding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationOnboarding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationOnboardingList) DeepCopyInto(out *ApplicationOnboardingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationOnboarding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationOnboardingList.
func (in *ApplicationOnboardingList) DeepCopy() *ApplicationOnboardingList {
	if in == nil {
		return nil
	}
	out := new(ApplicationOnboardingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationOnboardingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationOnboardingSpec) DeepCopyInto(out *ApplicationOnboardingSpec) {
	*out = *in
	if in.ZoneSettings != nil {
		in, out := &in.ZoneSettings, &out.ZoneSettings
		*out = make([]ZoneSetting, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AppInfo != nil {
		in, out := &in.AppInfo, &out.AppInfo
		*out = new(AppInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationOnboardingSpec.
func (in *ApplicationOnboardingSpec) DeepCopy() *ApplicationOnboardingSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationOnboardingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationOnboardingStatus) DeepCopyInto(out *ApplicationOnboardingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationOnboardingStatus.
func (in *ApplicationOnboardingStatus) DeepCopy() *ApplicationOnboardingStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationOnboardingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Artefact) DeepCopyInto(out *Artefact) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Artefact.
func (in *Artefact) DeepCopy() *Artefact {
	if in == nil {
		return nil
	}
	out := new(Artefact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Artefact) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtefactBody) DeepCopyInto(out *ArtefactBody) {
	*out = *in
	if in.ArtefactRepoLocation != nil {
		in, out := &in.ArtefactRepoLocation, &out.ArtefactRepoLocation
		*out = new(ArtefactRepoLocation)
		**out = **in
	}
	if in.ComponentSpec != nil {
		in, out := &in.ComponentSpec, &out.ComponentSpec
		*out = make([]ComponentSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtefactBody.
func (in *ArtefactBody) DeepCopy() *ArtefactBody {
	if in == nil {
		return nil
	}
	out := new(ArtefactBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtefactList) DeepCopyInto(out *ArtefactList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Artefact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtefactList.
func (in *ArtefactList) DeepCopy() *ArtefactList {
	if in == nil {
		return nil
	}
	out := new(ArtefactList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtefactList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtefactRepoLocation) DeepCopyInto(out *ArtefactRepoLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtefactRepoLocation.
func (in *ArtefactRepoLocation) DeepCopy() *ArtefactRepoLocation {
	if in == nil {
		return nil
	}
	out := new(ArtefactRepoLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtefactSpec) DeepCopyInto(out *ArtefactSpec) {
	*out = *in
	if in.ArtefactBody != nil {
		in, out := &in.ArtefactBody, &out.ArtefactBody
		*out = new(ArtefactBody)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtefactSpec.
func (in *ArtefactSpec) DeepCopy() *ArtefactSpec {
	if in == nil {
		return nil
	}
	out := new(ArtefactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtefactStatus) DeepCopyInto(out *ArtefactStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtefactStatus.
func (in *ArtefactStatus) DeepCopy() *ArtefactStatus {
	if in == nil {
		return nil
	}
	out := new(ArtefactStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssocPolicy) DeepCopyInto(out *AssocPolicy) {
	*out = *in
	in.AppIdList.DeepCopyInto(&out.AppIdList)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssocPolicy.
func (in *AssocPolicy) DeepCopy() *AssocPolicy {
	if in == nil {
		return nil
	}
	out := new(AssocPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityZone) DeepCopyInto(out *AvailabilityZone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityZone.
func (in *AvailabilityZone) DeepCopy() *AvailabilityZone {
	if in == nil {
		return nil
	}
	out := new(AvailabilityZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvailabilityZone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityZoneList) DeepCopyInto(out *AvailabilityZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AvailabilityZone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityZoneList.
func (in *AvailabilityZoneList) DeepCopy() *AvailabilityZoneList {
	if in == nil {
		return nil
	}
	out := new(AvailabilityZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvailabilityZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityZoneSpec) DeepCopyInto(out *AvailabilityZoneSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityZoneSpec.
func (in *AvailabilityZoneSpec) DeepCopy() *AvailabilityZoneSpec {
	if in == nil {
		return nil
	}
	out := new(AvailabilityZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityZoneStatus) DeepCopyInto(out *AvailabilityZoneStatus) {
	*out = *in
	if in.ReservedComputeResources != nil {
		in, out := &in.ReservedComputeResources, &out.ReservedComputeResources
		*out = make([]ComputeResourceInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComputeResourceQuotaLimits != nil {
		in, out := &in.ComputeResourceQuotaLimits, &out.ComputeResourceQuotaLimits
		*out = make([]ComputeResourceInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FlavoursSupported != nil {
		in, out := &in.FlavoursSupported, &out.FlavoursSupported
		*out = make([]FlavourSupported, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkResources != nil {
		in, out := &in.NetworkResources, &out.NetworkResources
		*out = new(NetworkResources)
		**out = **in
	}
	if in.ZoneServiceLevelObjsInfo != nil {
		in, out := &in.ZoneServiceLevelObjsInfo, &out.ZoneServiceLevelObjsInfo
		*out = new(ZoneServiceLevelObjsInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityZoneStatus.
func (in *AvailabilityZoneStatus) DeepCopy() *AvailabilityZoneStatus {
	if in == nil {
		return nil
	}
	out := new(AvailabilityZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Caps) DeepCopyInto(out *Caps) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Caps.
func (in *Caps) DeepCopy() *Caps {
	if in == nil {
		return nil
	}
	out := new(Caps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandLineParams) DeepCopyInto(out *CommandLineParams) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CommandArgs != nil {
		in, out := &in.CommandArgs, &out.CommandArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandLineParams.
func (in *CommandLineParams) DeepCopy() *CommandLineParams {
	if in == nil {
		return nil
	}
	out := new(CommandLineParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompEnvParam) DeepCopyInto(out *CompEnvParam) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompEnvParam.
func (in *CompEnvParam) DeepCopy() *CompEnvParam {
	if in == nil {
		return nil
	}
	out := new(CompEnvParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentSpec) DeepCopyInto(out *ComponentSpec) {
	*out = *in
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ComputeResourceProfile != nil {
		in, out := &in.ComputeResourceProfile, &out.ComputeResourceProfile
		*out = new(ComputeResourceProfile)
		**out = **in
	}
	if in.CommandLineParams != nil {
		in, out := &in.CommandLineParams, &out.CommandLineParams
		*out = new(CommandLineParams)
		(*in).DeepCopyInto(*out)
	}
	if in.ExposedInterfaces != nil {
		in, out := &in.ExposedInterfaces, &out.ExposedInterfaces
		*out = make([]ExposedInterfaceInfo, len(*in))
		copy(*out, *in)
	}
	if in.CompEnvParams != nil {
		in, out := &in.CompEnvParams, &out.CompEnvParams
		*out = make([]CompEnvParam, len(*in))
		copy(*out, *in)
	}
	if in.DeploymentConfig != nil {
		in, out := &in.DeploymentConfig, &out.DeploymentConfig
		*out = new(DeploymentConfig)
		**out = **in
	}
	if in.PersistentVolumes != nil {
		in, out := &in.PersistentVolumes, &out.PersistentVolumes
		*out = make([]PersistentVolume, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentSpec.
func (in *ComponentSpec) DeepCopy() *ComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeResourceInfo) DeepCopyInto(out *ComputeResourceInfo) {
	*out = *in
	if in.Gpu != nil {
		in, out := &in.Gpu, &out.Gpu
		*out = make([]GPUResource, len(*in))
		copy(*out, *in)
	}
	if in.Hugepages != nil {
		in, out := &in.Hugepages, &out.Hugepages
		*out = make([]Hugepage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeResourceInfo.
func (in *ComputeResourceInfo) DeepCopy() *ComputeResourceInfo {
	if in == nil {
		return nil
	}
	out := new(ComputeResourceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeResourceProfile) DeepCopyInto(out *ComputeResourceProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeResourceProfile.
func (in *ComputeResourceProfile) DeepCopy() *ComputeResourceProfile {
	if in == nil {
		return nil
	}
	out := new(ComputeResourceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfig) DeepCopyInto(out *DeploymentConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfig.
func (in *DeploymentConfig) DeepCopy() *DeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposedInterface) DeepCopyInto(out *ExposedInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposedInterface.
func (in *ExposedInterface) DeepCopy() *ExposedInterface {
	if in == nil {
		return nil
	}
	out := new(ExposedInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposedInterfaceInfo) DeepCopyInto(out *ExposedInterfaceInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposedInterfaceInfo.
func (in *ExposedInterfaceInfo) DeepCopy() *ExposedInterfaceInfo {
	if in == nil {
		return nil
	}
	out := new(ExposedInterfaceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Federation) DeepCopyInto(out *Federation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Federation.
func (in *Federation) DeepCopy() *Federation {
	if in == nil {
		return nil
	}
	out := new(Federation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Federation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationData) DeepCopyInto(out *FederationData) {
	*out = *in
	in.InitialDate.DeepCopyInto(&out.InitialDate)
	if in.RestOptions != nil {
		in, out := &in.RestOptions, &out.RestOptions
		*out = new(RestOptions)
		**out = **in
	}
	if in.K8sOptions != nil {
		in, out := &in.K8sOptions, &out.K8sOptions
		*out = new(K8sOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationData.
func (in *FederationData) DeepCopy() *FederationData {
	if in == nil {
		return nil
	}
	out := new(FederationData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationHealthInfo) DeepCopyInto(out *FederationHealthInfo) {
	*out = *in
	in.DateAndTimeZoneObject.DeepCopyInto(&out.DateAndTimeZoneObject)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationHealthInfo.
func (in *FederationHealthInfo) DeepCopy() *FederationHealthInfo {
	if in == nil {
		return nil
	}
	out := new(FederationHealthInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationList) DeepCopyInto(out *FederationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Federation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationList.
func (in *FederationList) DeepCopy() *FederationList {
	if in == nil {
		return nil
	}
	out := new(FederationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FederationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationSpec) DeepCopyInto(out *FederationSpec) {
	*out = *in
	if in.FederationData != nil {
		in, out := &in.FederationData, &out.FederationData
		*out = new(FederationData)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateData != nil {
		in, out := &in.UpdateData, &out.UpdateData
		*out = new(UpdateData)
		(*in).DeepCopyInto(*out)
	}
	if in.MobileNetworkIds != nil {
		in, out := &in.MobileNetworkIds, &out.MobileNetworkIds
		*out = new(MobileNetworkIds)
		(*in).DeepCopyInto(*out)
	}
	if in.FixedNetworkIds != nil {
		in, out := &in.FixedNetworkIds, &out.FixedNetworkIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationSpec.
func (in *FederationSpec) DeepCopy() *FederationSpec {
	if in == nil {
		return nil
	}
	out := new(FederationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationStatus) DeepCopyInto(out *FederationStatus) {
	*out = *in
	if in.UpdateDetails != nil {
		in, out := &in.UpdateDetails, &out.UpdateDetails
		*out = new(UpdateDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.EdgeDiscoveryServiceEndPoint != nil {
		in, out := &in.EdgeDiscoveryServiceEndPoint, &out.EdgeDiscoveryServiceEndPoint
		*out = new(ServiceEndpoint)
		(*in).DeepCopyInto(*out)
	}
	if in.LcmServiceEndPoint != nil {
		in, out := &in.LcmServiceEndPoint, &out.LcmServiceEndPoint
		*out = new(ServiceEndpoint)
		(*in).DeepCopyInto(*out)
	}
	if in.MobileNetworkIds != nil {
		in, out := &in.MobileNetworkIds, &out.MobileNetworkIds
		*out = new(MobileNetworkIds)
		(*in).DeepCopyInto(*out)
	}
	if in.FixedNetworkIds != nil {
		in, out := &in.FixedNetworkIds, &out.FixedNetworkIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ZoneDetails != nil {
		in, out := &in.ZoneDetails, &out.ZoneDetails
		*out = make([]ZoneDetails, len(*in))
		copy(*out, *in)
	}
	if in.PlatformCaps != nil {
		in, out := &in.PlatformCaps, &out.PlatformCaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.FederationExpiryDate.DeepCopyInto(&out.FederationExpiryDate)
	in.FederationRenewalDate.DeepCopyInto(&out.FederationRenewalDate)
	if in.FederationHealthInfo != nil {
		in, out := &in.FederationHealthInfo, &out.FederationHealthInfo
		*out = new(FederationHealthInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.DeviceConnStatusChangeCap != nil {
		in, out := &in.DeviceConnStatusChangeCap, &out.DeviceConnStatusChangeCap
		*out = new(Caps)
		**out = **in
	}
	if in.LocationRetrievalCap != nil {
		in, out := &in.LocationRetrievalCap, &out.LocationRetrievalCap
		*out = new(Caps)
		**out = **in
	}
	if in.UserPlaneMgmtEvtCap != nil {
		in, out := &in.UserPlaneMgmtEvtCap, &out.UserPlaneMgmtEvtCap
		*out = new(Caps)
		**out = **in
	}
	if in.DynamicQoSCap != nil {
		in, out := &in.DynamicQoSCap, &out.DynamicQoSCap
		*out = new(Caps)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationStatus.
func (in *FederationStatus) DeepCopy() *FederationStatus {
	if in == nil {
		return nil
	}
	out := new(FederationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlavourSupported) DeepCopyInto(out *FlavourSupported) {
	*out = *in
	if in.SupportedOSTypes != nil {
		in, out := &in.SupportedOSTypes, &out.SupportedOSTypes
		*out = make([]SupportedOSType, len(*in))
		copy(*out, *in)
	}
	if in.Gpu != nil {
		in, out := &in.Gpu, &out.Gpu
		*out = make([]GPUResource, len(*in))
		copy(*out, *in)
	}
	if in.Hugepages != nil {
		in, out := &in.Hugepages, &out.Hugepages
		*out = make([]Hugepage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlavourSupported.
func (in *FlavourSupported) DeepCopy() *FlavourSupported {
	if in == nil {
		return nil
	}
	out := new(FlavourSupported)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUResource) DeepCopyInto(out *GPUResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUResource.
func (in *GPUResource) DeepCopy() *GPUResource {
	if in == nil {
		return nil
	}
	out := new(GPUResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hugepage) DeepCopyInto(out *Hugepage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hugepage.
func (in *Hugepage) DeepCopy() *Hugepage {
	if in == nil {
		return nil
	}
	out := new(Hugepage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Image) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBody) DeepCopyInto(out *ImageBody) {
	*out = *in
	if in.ImgOSType != nil {
		in, out := &in.ImgOSType, &out.ImgOSType
		*out = new(ImgOSType)
		**out = **in
	}
	if in.ImageRepoLocation != nil {
		in, out := &in.ImageRepoLocation, &out.ImageRepoLocation
		*out = new(ImageRepoLocation)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBody.
func (in *ImageBody) DeepCopy() *ImageBody {
	if in == nil {
		return nil
	}
	out := new(ImageBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageList) DeepCopyInto(out *ImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Image, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageList.
func (in *ImageList) DeepCopy() *ImageList {
	if in == nil {
		return nil
	}
	out := new(ImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRepoLocation) DeepCopyInto(out *ImageRepoLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRepoLocation.
func (in *ImageRepoLocation) DeepCopy() *ImageRepoLocation {
	if in == nil {
		return nil
	}
	out := new(ImageRepoLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	if in.ImageBody != nil {
		in, out := &in.ImageBody, &out.ImageBody
		*out = new(ImageBody)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageStatus) DeepCopyInto(out *ImageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageStatus.
func (in *ImageStatus) DeepCopy() *ImageStatus {
	if in == nil {
		return nil
	}
	out := new(ImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImgOSType) DeepCopyInto(out *ImgOSType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImgOSType.
func (in *ImgOSType) DeepCopy() *ImgOSType {
	if in == nil {
		return nil
	}
	out := new(ImgOSType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JitterRanges) DeepCopyInto(out *JitterRanges) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JitterRanges.
func (in *JitterRanges) DeepCopy() *JitterRanges {
	if in == nil {
		return nil
	}
	out := new(JitterRanges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sOptions) DeepCopyInto(out *K8sOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sOptions.
func (in *K8sOptions) DeepCopy() *K8sOptions {
	if in == nil {
		return nil
	}
	out := new(K8sOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatencyRanges) DeepCopyInto(out *LatencyRanges) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatencyRanges.
func (in *LatencyRanges) DeepCopy() *LatencyRanges {
	if in == nil {
		return nil
	}
	out := new(LatencyRanges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MobileNetworkIds) DeepCopyInto(out *MobileNetworkIds) {
	*out = *in
	if in.Mncs != nil {
		in, out := &in.Mncs, &out.Mncs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MobileNetworkIds.
func (in *MobileNetworkIds) DeepCopy() *MobileNetworkIds {
	if in == nil {
		return nil
	}
	out := new(MobileNetworkIds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkResources) DeepCopyInto(out *NetworkResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkResources.
func (in *NetworkResources) DeepCopy() *NetworkResources {
	if in == nil {
		return nil
	}
	out := new(NetworkResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolume) DeepCopyInto(out *PersistentVolume) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolume.
func (in *PersistentVolume) DeepCopy() *PersistentVolume {
	if in == nil {
		return nil
	}
	out := new(PersistentVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestOptions) DeepCopyInto(out *RestOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestOptions.
func (in *RestOptions) DeepCopy() *RestOptions {
	if in == nil {
		return nil
	}
	out := new(RestOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	if in.ServiceCaps != nil {
		in, out := &in.ServiceCaps, &out.ServiceCaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApiRoutingInfo != nil {
		in, out := &in.ApiRoutingInfo, &out.ApiRoutingInfo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpoint) DeepCopyInto(out *ServiceEndpoint) {
	*out = *in
	if in.Ipv4Addresses != nil {
		in, out := &in.Ipv4Addresses, &out.Ipv4Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ipv6Addresses != nil {
		in, out := &in.Ipv6Addresses, &out.Ipv6Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpoint.
func (in *ServiceEndpoint) DeepCopy() *ServiceEndpoint {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupportedOSType) DeepCopyInto(out *SupportedOSType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupportedOSType.
func (in *SupportedOSType) DeepCopy() *SupportedOSType {
	if in == nil {
		return nil
	}
	out := new(SupportedOSType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThroughputRanges) DeepCopyInto(out *ThroughputRanges) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThroughputRanges.
func (in *ThroughputRanges) DeepCopy() *ThroughputRanges {
	if in == nil {
		return nil
	}
	out := new(ThroughputRanges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateData) DeepCopyInto(out *UpdateData) {
	*out = *in
	if in.AssocAppPolicies != nil {
		in, out := &in.AssocAppPolicies, &out.AssocAppPolicies
		*out = new(AssocPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.AssocOpsPolicies != nil {
		in, out := &in.AssocOpsPolicies, &out.AssocOpsPolicies
		*out = new(AssocPolicy)
		(*in).DeepCopyInto(*out)
	}
	in.ModificationDate.DeepCopyInto(&out.ModificationDate)
	if in.AddMobileNetworkIds != nil {
		in, out := &in.AddMobileNetworkIds, &out.AddMobileNetworkIds
		*out = new(MobileNetworkIds)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoveMobileNetworkIds != nil {
		in, out := &in.RemoveMobileNetworkIds, &out.RemoveMobileNetworkIds
		*out = new(MobileNetworkIds)
		(*in).DeepCopyInto(*out)
	}
	if in.AddFixedNetworkIds != nil {
		in, out := &in.AddFixedNetworkIds, &out.AddFixedNetworkIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemoveFixedNetworkIds != nil {
		in, out := &in.RemoveFixedNetworkIds, &out.RemoveFixedNetworkIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateData.
func (in *UpdateData) DeepCopy() *UpdateData {
	if in == nil {
		return nil
	}
	out := new(UpdateData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateDetails) DeepCopyInto(out *UpdateDetails) {
	*out = *in
	in.UpdateDate.DeepCopyInto(&out.UpdateDate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateDetails.
func (in *UpdateDetails) DeepCopy() *UpdateDetails {
	if in == nil {
		return nil
	}
	out := new(UpdateDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneDetails) DeepCopyInto(out *ZoneDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneDetails.
func (in *ZoneDetails) DeepCopy() *ZoneDetails {
	if in == nil {
		return nil
	}
	out := new(ZoneDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneInfo) DeepCopyInto(out *ZoneInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneInfo.
func (in *ZoneInfo) DeepCopy() *ZoneInfo {
	if in == nil {
		return nil
	}
	out := new(ZoneInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneServiceLevelObjsInfo) DeepCopyInto(out *ZoneServiceLevelObjsInfo) {
	*out = *in
	if in.LatencyRanges != nil {
		in, out := &in.LatencyRanges, &out.LatencyRanges
		*out = new(LatencyRanges)
		**out = **in
	}
	if in.JitterRanges != nil {
		in, out := &in.JitterRanges, &out.JitterRanges
		*out = new(JitterRanges)
		**out = **in
	}
	if in.ThroughputRanges != nil {
		in, out := &in.ThroughputRanges, &out.ThroughputRanges
		*out = new(ThroughputRanges)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneServiceLevelObjsInfo.
func (in *ZoneServiceLevelObjsInfo) DeepCopy() *ZoneServiceLevelObjsInfo {
	if in == nil {
		return nil
	}
	out := new(ZoneServiceLevelObjsInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneSetting) DeepCopyInto(out *ZoneSetting) {
	*out = *in
	if in.ZoneId != nil {
		in, out := &in.ZoneId, &out.ZoneId
		*out = make([]ZoneIdString, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneSetting.
func (in *ZoneSetting) DeepCopy() *ZoneSetting {
	if in == nil {
		return nil
	}
	out := new(ZoneSetting)
	in.DeepCopyInto(out)
	return out
}
